"""initial migration

Revision ID: e1258307c21a
Revises: 
Create Date: 2025-11-11 18:05:59.707026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1258307c21a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_stream_viewers_livestream_status'), table_name='stream_viewers')
    op.drop_table('stream_viewers')
    op.drop_index(op.f('idx_playlists_member'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_table('service_times')
    op.drop_index(op.f('idx_role_permissions_role'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_recipient'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('sermon_downloads')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('settings')
    op.drop_index(op.f('idx_token_blacklist_created_at'), table_name='token_blacklist')
    op.drop_index(op.f('idx_token_blacklist_user_created'), table_name='token_blacklist')
    op.drop_index(op.f('idx_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('idx_playlist_sermons_playlist'), table_name='playlist_sermons')
    op.drop_table('playlist_sermons')
    op.drop_table('content')
    op.drop_index(op.f('idx_attendance_date'), table_name='attendance')
    op.drop_index(op.f('idx_attendance_user'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('idx_forms_status'), table_name='forms')
    op.drop_table('forms')
    op.drop_table('permissions')
    op.drop_table('moderation_logs')
    op.drop_index(op.f('idx_form_responses_form'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('idx_announcements_publish_date'), table_name='announcements')
    op.drop_index(op.f('idx_announcements_status'), table_name='announcements')
    op.create_index(op.f('ix_announcements_publish_date'), 'announcements', ['publish_date'], unique=False)
    op.create_index(op.f('ix_announcements_status'), 'announcements', ['status'], unique=False)
    op.drop_column('announcements', 'send_sms')
    op.drop_column('announcements', 'send_email')
    op.drop_index(op.f('idx_chat_messages_livestream'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_time'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_livestream_id'), 'chat_messages', ['livestream_id'], unique=False)
    op.drop_constraint(op.f('event_registrations_event_id_member_id_key'), 'event_registrations', type_='unique')
    op.drop_index(op.f('idx_event_registrations_event'), table_name='event_registrations')
    op.drop_index(op.f('idx_event_registrations_member'), table_name='event_registrations')
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_member_id'), 'event_registrations', ['member_id'], unique=False)
    op.create_foreign_key(None, 'event_registrations', 'users', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_events_date'), table_name='events')
    op.drop_index(op.f('idx_events_status'), table_name='events')
    op.create_index(op.f('ix_events_date'), 'events', ['date'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.drop_column('events', 'registration_required')
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'cost')
    op.drop_column('events', 'organizer')
    op.drop_column('events', 'recurring_type')
    op.drop_column('events', 'recurring')
    op.drop_column('events', 'registration_deadline')
    op.drop_index(op.f('idx_giving_date'), table_name='giving')
    op.drop_index(op.f('idx_giving_date_type'), table_name='giving')
    op.drop_index(op.f('idx_giving_member'), table_name='giving')
    op.drop_index(op.f('idx_giving_member_date'), table_name='giving')
    op.drop_index(op.f('idx_giving_member_type'), table_name='giving')
    op.drop_index(op.f('idx_giving_type'), table_name='giving')
    op.create_index(op.f('ix_giving_date'), 'giving', ['date'], unique=False)
    op.create_index(op.f('ix_giving_member_id'), 'giving', ['member_id'], unique=False)
    op.create_index(op.f('ix_giving_type'), 'giving', ['type'], unique=False)
    op.create_foreign_key(None, 'giving', 'users', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_prayer_requests_member'), table_name='prayer_requests')
    op.drop_index(op.f('idx_prayer_requests_status'), table_name='prayer_requests')
    op.create_index(op.f('ix_prayer_requests_member_id'), 'prayer_requests', ['member_id'], unique=False)
    op.create_index(op.f('ix_prayer_requests_status'), 'prayer_requests', ['status'], unique=False)
    op.create_foreign_key(None, 'prayer_requests', 'users', ['member_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sermons', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_sermons_date'), table_name='sermons')
    op.drop_index(op.f('idx_sermons_series'), table_name='sermons')
    op.drop_index(op.f('idx_sermons_speaker'), table_name='sermons')
    op.drop_index(op.f('idx_sermons_speaker_search'), table_name='sermons', postgresql_using='gin')
    op.drop_index(op.f('idx_sermons_title_search'), table_name='sermons', postgresql_using='gin')
    op.create_index(op.f('ix_sermons_date'), 'sermons', ['date'], unique=False)
    op.create_index(op.f('ix_sermons_series_id'), 'sermons', ['series_id'], unique=False)
    op.create_index(op.f('ix_sermons_speaker'), 'sermons', ['speaker'], unique=False)
    op.drop_column('sermons', 'downloads')
    op.alter_column('users', 'date_joined',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('users', 'membership_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_membership_status'), 'users', ['membership_status'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('users', 'notification_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_membership_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'membership_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('users', 'date_joined',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.add_column('sermons', sa.Column('downloads', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sermons_speaker'), table_name='sermons')
    op.drop_index(op.f('ix_sermons_series_id'), table_name='sermons')
    op.drop_index(op.f('ix_sermons_date'), table_name='sermons')
    op.create_index(op.f('idx_sermons_title_search'), 'sermons', [sa.literal_column("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_sermons_speaker_search'), 'sermons', [sa.literal_column("to_tsvector('english'::regconfig, speaker::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_sermons_speaker'), 'sermons', ['speaker'], unique=False)
    op.create_index(op.f('idx_sermons_series'), 'sermons', ['series_id'], unique=False)
    op.create_index(op.f('idx_sermons_date'), 'sermons', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('sermons', 'tags',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_constraint(None, 'prayer_requests', type_='foreignkey')
    op.drop_index(op.f('ix_prayer_requests_status'), table_name='prayer_requests')
    op.drop_index(op.f('ix_prayer_requests_member_id'), table_name='prayer_requests')
    op.create_index(op.f('idx_prayer_requests_status'), 'prayer_requests', ['status'], unique=False)
    op.create_index(op.f('idx_prayer_requests_member'), 'prayer_requests', ['member_id'], unique=False)
    op.drop_constraint(None, 'giving', type_='foreignkey')
    op.drop_index(op.f('ix_giving_type'), table_name='giving')
    op.drop_index(op.f('ix_giving_member_id'), table_name='giving')
    op.drop_index(op.f('ix_giving_date'), table_name='giving')
    op.create_index(op.f('idx_giving_type'), 'giving', ['type'], unique=False)
    op.create_index(op.f('idx_giving_member_type'), 'giving', ['member_id', 'type'], unique=False)
    op.create_index(op.f('idx_giving_member_date'), 'giving', ['member_id', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_giving_member'), 'giving', ['member_id'], unique=False)
    op.create_index(op.f('idx_giving_date_type'), 'giving', [sa.literal_column('date DESC'), 'type'], unique=False)
    op.create_index(op.f('idx_giving_date'), 'giving', [sa.literal_column('date DESC')], unique=False)
    op.add_column('events', sa.Column('registration_deadline', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('recurring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('recurring_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('organizer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('registration_required', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_date'), table_name='events')
    op.create_index(op.f('idx_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('idx_events_date'), 'events', [sa.literal_column('date DESC')], unique=False)
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.drop_index(op.f('ix_event_registrations_member_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.create_index(op.f('idx_event_registrations_member'), 'event_registrations', ['member_id'], unique=False)
    op.create_index(op.f('idx_event_registrations_event'), 'event_registrations', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('event_registrations_event_id_member_id_key'), 'event_registrations', ['event_id', 'member_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_chat_messages_livestream_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_time'), 'chat_messages', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_chat_messages_livestream'), 'chat_messages', ['livestream_id'], unique=False)
    op.add_column('announcements', sa.Column('send_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('send_sms', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_announcements_status'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_publish_date'), table_name='announcements')
    op.create_index(op.f('idx_announcements_status'), 'announcements', ['status'], unique=False)
    op.create_index(op.f('idx_announcements_publish_date'), 'announcements', [sa.literal_column('publish_date DESC')], unique=False)
    op.create_table('form_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('form_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('form_responses_form_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('form_responses_pkey'))
    )
    op.create_index(op.f('idx_form_responses_form'), 'form_responses', ['form_id'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('viewer_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('moderation_logs_pkey'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('name', name='permissions_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('forms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('responses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('allow_multiple', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('require_login', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('template', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'closed'::character varying]::text[])", name=op.f('forms_status_check')),
    sa.CheckConstraint("type::text = ANY (ARRAY['registration'::character varying, 'survey'::character varying, 'feedback'::character varying, 'application'::character varying]::text[])", name=op.f('forms_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('forms_pkey'))
    )
    op.create_index(op.f('idx_forms_status'), 'forms', ['status'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('present', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendance_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey')),
    sa.UniqueConstraint('user_id', 'date', 'service_type', name=op.f('attendance_user_id_date_service_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_attendance_user'), 'attendance', ['user_id'], unique=False)
    op.create_index(op.f('idx_attendance_date'), 'attendance', [sa.literal_column('date DESC')], unique=False)
    op.create_table('content',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('content_pkey')),
    sa.UniqueConstraint('key', name=op.f('content_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('playlist_sermons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sermon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('playlist_sermons_playlist_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('playlist_sermons_sermon_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_sermons_pkey')),
    sa.UniqueConstraint('playlist_id', 'sermon_id', name=op.f('playlist_sermons_playlist_id_sermon_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_playlist_sermons_playlist'), 'playlist_sermons', ['playlist_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('idx_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_index(op.f('idx_token_blacklist_user_created'), 'token_blacklist', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_token_blacklist_created_at'), 'token_blacklist', ['created_at'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey')),
    sa.UniqueConstraint('key', name=op.f('settings_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('device', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.CheckConstraint("severity::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])", name=op.f('audit_logs_severity_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_index(op.f('idx_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('sermon_downloads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('sermon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('downloaded_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('sermon_downloads_sermon_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sermon_downloads_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sermon_downloads_pkey')),
    sa.UniqueConstraint('sermon_id', 'user_id', name=op.f('sermon_downloads_sermon_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])", name=op.f('notifications_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('idx_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('idx_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('idx_notifications_recipient'), 'notifications', ['recipient_email', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_permission_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('role_permissions_pkey')),
    sa.UniqueConstraint('role', 'permission_id', name=op.f('role_permissions_role_permission_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('service_times',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('service_times_pkey'))
    )
    op.create_table('playlists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playlists_pkey'))
    )
    op.create_index(op.f('idx_playlists_member'), 'playlists', ['member_id'], unique=False)
    op.create_table('stream_viewers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('livestream_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('stream_viewers_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('stream_viewers_pkey'))
    )
    op.create_index(op.f('idx_stream_viewers_livestream_status'), 'stream_viewers', ['livestream_id', 'status'], unique=False)
    # ### end Alembic commands ###
